language: node_js
node_js:
  - "node"
# use most current stable node version, can specify a version if you need to
cache:
  directories:
    - "node_modules"
script:
  - ./scripts/build.sh
  - ./scripts/test.sh